"""remove task_configs table inline config on task

Revision ID: 545def037c93
Revises: 044d9ddc000a
Create Date: 2026-03-19 12:41:08.704377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "545def037c93"
down_revision: Union[str, Sequence[str], None] = "044d9ddc000a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop FK constraint first, then columns, then the referenced table
    op.drop_constraint(op.f("tasks_config_id_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "params")
    op.drop_column("tasks", "config_id")

    op.drop_index(op.f("ix_task_configs_params_hash"), table_name="task_configs")
    op.drop_index(op.f("ix_task_configs_task_type"), table_name="task_configs")
    op.drop_table("task_configs")

    # Add new columns — nullable first so existing rows won't fail, then constrain
    op.add_column("tasks", sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("tasks", sa.Column("config_hash", sa.String(length=64), nullable=True))
    op.execute("UPDATE tasks SET config = '{}', config_hash = md5('labeling:{}') WHERE config IS NULL")
    op.alter_column("tasks", "config", nullable=False)
    op.alter_column("tasks", "config_hash", nullable=False)
    op.create_index(op.f("ix_tasks_config_hash"), "tasks", ["config_hash"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("config_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "tasks", sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("tasks_config_id_fkey"), "tasks", "task_configs", ["config_id"], ["config_id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_tasks_config_hash"), table_name="tasks")
    op.drop_column("tasks", "config_hash")
    op.drop_column("tasks", "config")
    op.create_table(
        "task_configs",
        sa.Column("config_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("task_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("params_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("config_id", name=op.f("task_configs_pkey")),
    )
    op.create_index(op.f("ix_task_configs_task_type"), "task_configs", ["task_type"], unique=False)
    op.create_index(op.f("ix_task_configs_params_hash"), "task_configs", ["params_hash"], unique=True)
    # ### end Alembic commands ###
